# Generated by Django 3.0.2 on 2020-01-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardApi', '0003_auto_20200120_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcards',
            old_name='instruction',
            new_name='instructions',
        ),
    ]
